### ISSUE TITLE
I need help with flans mod

### ISSUE THREAD

**Issue by KingplaysYT** [KingplaysYT/Flansmod#2]
---- Minecraft Crash Report ----

WARNING: coremods are present:
Inventory Tweaks Coremod (gefahr3.jar)
DLFMLCorePlugin (gefahr (2).jar)
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
llibrary (llibrary-core-1.0.11-1.12.2.jar)
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
GSHooksLoader (GalaxySpace-1.12.2-2.0.15.jar)
wings (Wings-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 2/9/21 8:52 PM
Description: Initializing game

java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
at growthcraft.core.shared.definition.BlockTypeDefinition.registerBlock(BlockTypeDefinition.java:116)
at growthcraft.cellar.common.Init.registerBlocks(Init.java:72)
at growthcraft.cellar.GrowthcraftCellar.registerBlocks(GrowthcraftCellar.java:130)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_373_GrowthcraftCellar_registerBlocks_Register.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:295)
at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
at growthcraft.core.shared.definition.BlockTypeDefinition.registerBlock(BlockTypeDefinition.java:116)
at growthcraft.cellar.common.Init.registerBlocks(Init.java:72)
at growthcraft.cellar.GrowthcraftCellar.registerBlocks(GrowthcraftCellar.java:130)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_373_GrowthcraftCellar_registerBlocks_Register.invoke(.dynamic)
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 600033056 bytes (572 MB) / 2717908992 bytes (2592 MB) up to 8589934592 bytes (8192 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 97 mods loaded, 96 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

| State | ID | Version | Source | Signature |
|:----- |:--------------------------- |:------------------------ |:---------------------------------------------- |:---------------------------------------- |
| LCH | minecraft | 1.12.2 | minecraft.jar | None |
| LCH | mcp | 9.42 | minecraft.jar | None |
| LCH | FML | 8.0.99.99 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCH | forge | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCH | micdoodlecore | | minecraft.jar | None |
| LCH | openmodscore | 0.12.2 | minecraft.jar | None |
| LCH | securitycraft | v1.8.20.2 | [1.12.2]+SecurityCraft+v1.8.20.2.jar | None |
| LCH | damageindicatorsmod | 1.0 | [1.12.2]DamageIndicatorsMod-3.5.1.jar | None |
| LCH | aoa3 | 3.3.6 | AoA3-3.3.6.jar | 8bddeac148843f40e0b9f69201be2f4b3071700d |
| LCH | applecore | 3.2.0 | AppleCore-mc1.12.2-3.2.0.jar | None |
| LCH | ic2 | 2.8.186-ex112 | Industrial-Craft-2-Mod-Experimental-1.12.2.jar | de041f9f6187debbc77034a344134053277aa3b0 |
| LCH | galacticraftcore | 4.0.2.281 | GalacticraftCore-1.12.2-4.0.2.281.jar | None |
| LCH | galacticraftplanets | 4.0.2.281 | Galacticraft-Planets-1.12.2-4.0.2.281.jar | None |
| LCH | asmodeuscore | 0.0.24 | AsmodeusCore-1.12.2-0.0.24.jar | None |
| LCH | get_back_to_home | 1.5 | BackToHome-1.5.jar | None |
| LCH | baubles | 1.5.2 | Baubles-1.12-1.5.2.jar | None |
| LCH | betteranimationscollection2 | 1.0.2 | BetterAnimationsCollection2-v1.0.2-1.12.2.jar | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
| LCH | bettercaves | 1.12.2 | bettercaves-1.12.2-1.5.0.jar | None |
| LCH | better_diving | 1.5.1 | BetterDiving-1.12.2-1.5.1.jar | None |
| LCH | bibliocraft | 2.4.5 | BiblioCraft[v2.4.5][MC1.12.2].jar | None |
| LCH | blockcraftery | 1.12.2-1.3.1 | blockcraftery-1.12.2-1.3.1.jar | None |
| LCH | guideapi | 1.12-2.1.8-63 | Guide-API-1.12-2.1.8-63.jar | None |
| LCH | bloodmagic | 1.12.2-2.4.3-105 | BloodMagic-1.12.2-2.4.3-105.jar | None |
| LCH | jei | 4.15.0.293 | jei_1.12.2-4.15.0.293.jar | None |
| LCH | thaumcraft | 6.1.BETA26 | Thaumcraft-1.12.2-6.1.BETA26.jar | None |
| LCH | botania | r1.10-363 | Botania+r1.10-363.jar | None |
| LCH | ctm | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar | None |
| LCH | chisel | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar | None |
| LCH | chococraft | 0.9.1.52 | chococraft_1.12.1-0.9.1.52.jar | None |
| LCH | cookingforblockheads | 6.5.0 | CookingForBlockheads_1.12.2-6.5.0.jar | None |
| LCH | customnpcs | 1.12 | CustomNPCs_1.12.2-(01Oct19).jar | None |
| LCH | doggytalents | 1.15.1.5 | DoggyTalents-1.12.2-1.15.1.5.jar | None |
| LCH | dynamictrees | 1.12.2-0.9.7 | DynamicTrees-1.12.2-0.9.7.jar | None |
| LCH | exoticbirds | 1.0 | Exotic+Birds+1.12.2-3.1.0.jar | None |
| LCH | mjrlegendslib | 1.12.2-1.2.0 | MJRLegendsLib-1.12.2-1.2.0.jar | b02331787272ec3515ebe63ecdeea0d746653468 |
| LCH | spacecraftx | 1.0.35 | spacecraftx-1.12.2-1.0.35.jar | None |
| LCH | zollerngalaxy | 2.0.23 | ZollernGalaxy-1.12.2-v2.0.23.jar | None |
| LCH | extraplanets | 1.12.2-0.7.1 | ExtraPlanets-1.12.2-0.7.1.jar | b02331787272ec3515ebe63ecdeea0d746653468 |
| LCH | flansmod | 5.7.2 | Flan's+Mod-1.12.2-5.7.2.jar | None |
| LCH | cfm | 6.3.1 | furniture-6.3.1-1.12.2.jar | None |
| LCH | galaxyspace | 2.0.15 | GalaxySpace-1.12.2-2.0.15.jar | None |
| LCH | dynamiclights | 1.4.9 | gefahr (2).jar | None |
| LCH | dynamiclights_onfire | 1.0.7 | gefahr (2).jar | None |
| LCH | dynamiclights_creepers | 1.0.6 | gefahr (2).jar | None |
| LCH | dynamiclights_dropitems | 1.1.0 | gefahr (2).jar | None |
| LCH | dynamiclights_entityclasses | 1.0.1 | gefahr (2).jar | None |
| LCH | dynamiclights_mobequipment | 1.1.0 | gefahr (2).jar | None |
| LCH | dynamiclights_flamearrows | 1.0.1 | gefahr (2).jar | None |
| LCH | dynamiclights_floodlights | 1.0.3 | gefahr (2).jar | None |
| LCH | dynamiclights_otherplayers | 1.0.9 | gefahr (2).jar | None |
| LCH | dynamiclights_theplayer | 1.1.3 | gefahr (2).jar | None |
| LCH | controlling | 3.0.9 | gefahr.jar | None |
| LCH | inventorytweaks | 1.63+release.109.220f184 | gefahr3.jar | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
| LCH | gravestone | 1.10.3 | gravestone-1.10.3.jar | None |
| LCH | growthcraft | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_apples | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_bamboo | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_cellar | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_bees | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_fishtrap | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_grapes | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_hops | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_milk | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | growthcraft_rice | 4.1.0 | GrowthCraft-Mod-1.12.2.jar | None |
| LCH | harvestcraft | 1.12.2zb | HarvestCraft-Mod-1.12.2.jar | None |
| LCH | ichunutil | 7.2.2 | iChunUtil-1.12.2-7.2.2.jar | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
| LCH | inventorypets | 2.0.6 | inventorypets-1.12-2.0.10.jar | None |
| LCH | journeymap | 1.12.2-5.7.1 | journeymap-1.12.2-5.7.1.jar | None |
| LCH | karatgarden | 0.1.4 | KaratGarden-0.1.4-[1.12.2].jar | None |
| LCH | lycanitesmobs | 2.0.7.2 - MC 1.12.2 | lycanitesmobs-1.12.2-2.0.7.2.jar | None |
| LCH | malisiscore | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar | None |
| LCH | malisisdoors | 1.12.2-7.3.0 | malisisdoors-1.12.2-7.3.0.jar | None |
| LCH | mca | 6.0.1 | MCA-1.12.2-6.0.1-universal.jar | None |
| LCH | mekanism | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar | None |
| LCH | stevekung's_lib | 1.1.9 | SteveKunG's-Lib-1.12.2-1.1.9.jar | None |
| LCH | moreplanets | 2.2.1 | More-Planets-1.12.2-2.2.1-GC280.jar | None |
| LCH | morearmor | 1.3.5 | MoreArmor-1-3-5.jar | None |
| LCH | llibrary | 1.7.20 | llibrary-1.7.20-1.12.2.jar | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
| LCH | mowziesmobs | 1.5.4 | mowziesmobs-1.5.4.jar | None |
| LCH | openmods | 0.12.2 | OpenModsLib-1.12.2-0.12.2.jar | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
| LCH | oreexcavation | 1.4.150 | OreExcavation-1.4.150.jar | None |
| LCH | portalgun | 7.1.0 | PortalGun-1.12.2-7.1.0.jar | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
| LCH | ptrmodellib | 1.0.4 | PTRLib-1.0.4.jar | None |
| LCH | radixcore | 1.12.x-2.2.1 | RadixCore-1.12.x-2.2.1-universal.jar | None |
| LCH | shetiphiancore | 3.5.9 | shetiphiancore-1.12.0-3.5.9.jar | None |
| LCH | terraqueous | 1.4.17 | terraqueous-1.12.2-1.4.17b.jar | None |
| LCH | travelersbackpack | 1.0.35 | TravelersBackpack-1.12.2-1.0.35.jar | None |
| LCH | ultimate_unicorn_mod | 1.5.17 | ultimate_unicorn_mod-1.12.2-1.5.17.jar | None |
| LCH | wings | 1.1.4 | Wings-Mod-1.12.2.jar | None |
| LCH | bauble_wings | 1.0.0 | Wings-Mod-1.12.2.jar | None |
| LCH | xlfoodmod | 1.12.2-1.9.2 | XL-Food-Mod-1.12.2-1.9.2.jar | None |
| LCH | zoocraftdiscoveries | 1.0 | Zoocraft+Discoveries+1.12.2-1.3.0.jar | None |
| LCH | betteranimalsplus | 9.0.1 | betteranimalsplus-1.12.2-9.0.1.jar | None |
| LCH | jurassicraft | 2.2.9 | JurassiCraft-1.12.2-2.2.9.jar | None |
| LCH | kiwi | 0.5.3.32 | Kiwi-1.12.2-0.5.3.32.jar | None |
| LCH | mysticallib | 1.12.2-1.7.0 | mysticallib-1.12.2-1.7.0.jar | None |
| UD | mobends_wings | 1.0.0 | Wings-Mod-1.12.2.jar | None |

Loaded coremods (and transformers):
Inventory Tweaks Coremod (gefahr3.jar)
invtweaks.forge.asm.ContainerTransformer
DLFMLCorePlugin (gefahr (2).jar)
atomicstryker.dynamiclights.common.DLTransformer
SteveKunGLibPlugin (SteveKunG's-Lib-1.12.2-1.1.9.jar)

AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
squeek.applecore.asm.TransformerModuleHandler
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
mekanism.coremod.KeybindingMigrationHelper
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
openmods.core.OpenModsClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
team.chisel.ctm.client.asm.CTMTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
shetiphian.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.281.jar)
micdoodle8.mods.miccore.MicdoodleTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)

GSHooksLoader (GalaxySpace-1.12.2-2.0.15.jar)
galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
wings (Wings-Mod-1.12.2.jar)
me.paulf.wings.server.asm.WingsRuntimePatcher
me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14758 Compatibility Profile Context 21.1.1 27.20.14527.2002' Renderer: 'Radeon RX 580 Series'
OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
Launched Version: 1.12.2-forge-14.23.5.2854
LWJGL: 2.9.4
OpenGL: Radeon RX 580 Series GL version 4.6.14758 Compatibility Profile Context 21.1.1 27.20.14527.2002, ATI Technologies Inc.
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: OmaKnock25K.zip
Current Language: Deutsch (Deutschland)
Profiler Position: N/A (disabled)
CPU: 12x AMD Ryzen 5 3600 6-Core Processor
OptiFine Version: OptiFine_1.12.2_HD_U_G5
OptiFine Build: 20210124-142939
Render Distance Chunks: 12
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.6.14758 Compatibility Profile Context 21.1.1 27.20.14527.2002
OpenGlRenderer: Radeon RX 580 Series
OpenGlVendor: ATI Technologies Inc.
CpuCount: 12

i dont know what to do

**Comment by KingplaysYT** [comment]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
Exit Code: -1

That was the error code
